# Generated by Django 3.1.4 on 2020-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('amount', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('highest_price_day', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lowest_price_day', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('day_variation', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('month_variation', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('year_variation', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
