# Generated by Django 3.1.4 on 2020-12-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='day_variation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='highest_price_day',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lowest_price_day',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='month_variation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='year_variation',
        ),
    ]
