# Generated by Django 3.1.4 on 2020-12-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20201221_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbuy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='stocksale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
