# Generated by Django 3.1.4 on 2020-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201221_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbuy',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
