# Generated by Django 3.1.4 on 2020-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201222_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbuy',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stocksale',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
